# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mascota' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mascota
  pod 'lottie-ios'
  pod 'Moya', '~> 14.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'SwiftLint'
  pod 'FSCalendar'


  target 'MascotaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MascotaUITests' do
    # Pods for testing
  end

end
